### ISSUE TITLE
Problems with German Umlauts

### ISSUE THREAD

**Issue by monofox** [theunraveler/taskwarrior-web#60] opened 2013-10-04 17:15 UTC
Hello guys.

Thank you for your works. 
While working with it i've got the problem, that it's not working correctly with german umlauts "ä", "ö", "ü":

```

application error
Encoding::InvalidByteSequenceError at /tasks/pending
"\xC3" on US-ASCII

    file: common.rb
    location: encode
    line: 155

BACKTRACE

(expand)

JUMP TO: GET POST COOKIES ENV

    /usr/lib/ruby/1.9.1/webrick/httpserver.rb in service
        si.service(req, res)
    /usr/lib/ruby/1.9.1/webrick/httpserver.rb in run
        server.service(req, res)
    /usr/lib/ruby/1.9.1/webrick/server.rb in block in start_thread
        block ? block.call(sock) : run(sock)

GET

No GET data.
POST

No POST data.
COOKIES
Variable    Value
rack.session    
"BAh7B0kiD3Nlc3Npb25faWQGOgZFRiJFZmFhN2E2ZTQzNWNjMDVjOTdmNGI1\nYmQ0ZDc1MjgxY2Q5NDY0MjI4YzQ5MDJjYTg5MzEyMjAzN2RmYTQyNWM4YUki\nDXRyYWNraW5nBjsARnsISSIUSFRUUF9VU0VSX0FHRU5UBjsARiItZmEwMjcx\nZTZjYjcxOTg5YmRkYmNmMThjODI3NjZjZGU3NjQwMWNiNkkiGUhUVFBfQUND\nRVBUX0VOQ09ESU5HBjsARiItYTBiZmM4NzZkNjhmZTdhZWE3MDBkYTVlYTg5\nMjVhYmFjNmYyZjc5NEkiGUhUVFBfQUNDRVBUX0xBTkdVQUdFBjsARiItYWJm\nMDQ5YzA0M2QzZDVlM2RhNzkyNjU4N2VkYjRhMmM5OThhMTIyYQ==\n--ef3d5b870adc10cba280e0ef95861f98201af55b"
Rack ENV
Variable    Value
GATEWAY_INTERFACE   
CGI/1.1
HTTP_ACCEPT     
text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
HTTP_ACCEPT_ENCODING    
gzip, deflate
HTTP_ACCEPT_LANGUAGE    
de-de,en-us;q=0.7,en;q=0.3
HTTP_CONNECTION     
close
HTTP_COOKIE     
rack.session=BAh7B0kiD3Nlc3Npb25faWQGOgZFRiJFZmFhN2E2ZTQzNWNjMDVjOTdmNGI1%0AYmQ0ZDc1MjgxY2Q5NDY0MjI4YzQ5MDJjYTg5MzEyMjAzN2RmYTQyNWM4YUki%0ADXRyYWNraW5nBjsARnsISSIUSFRUUF9VU0VSX0FHRU5UBjsARiItZmEwMjcx%0AZTZjYjcxOTg5YmRkYmNmMThjODI3NjZjZGU3NjQwMWNiNkkiGUhUVFBfQUND%0ARVBUX0VOQ09ESU5HBjsARiItYTBiZmM4NzZkNjhmZTdhZWE3MDBkYTVlYTg5%0AMjVhYmFjNmYyZjc5NEkiGUhUVFBfQUNDRVBUX0xBTkdVQUdFBjsARiItYWJm%0AMDQ5YzA0M2QzZDVlM2RhNzkyNjU4N2VkYjRhMmM5OThhMTIyYQ%3D%3D%0A--ef3d5b870adc10cba280e0ef95861f98201af55b
HTTP_DNT    
1
HTTP_HOST   
task.xxxxxx.de
HTTP_USER_AGENT     
Mozilla/5.0 (X11; Linux x86_64; rv:23.0) Gecko/20100101 Firefox/23.0
HTTP_VERSION    
HTTP/1.1
HTTP_X_FORWARDED_FOR    
0.0.0.0
HTTP_X_REAL_IP  
0.0.0.0
PATH_INFO   
/tasks/pending
QUERY_STRING    
REMOTE_ADDR     
127.0.0.1
REMOTE_HOST     
localhost.localdomain
REQUEST_METHOD  
GET
REQUEST_PATH    
/tasks/pending
REQUEST_URI     
http://task.xxxxxx.de/tasks/pending
SCRIPT_NAME     
SERVER_NAME     
task.xxxxxxxx.de
SERVER_PORT     
80
SERVER_PROTOCOL     
HTTP/1.1
SERVER_SOFTWARE     
WEBrick/1.3.1 (Ruby/1.9.3/2012-04-20)
rack.errors     
#<Object:0x00000000d251b8>
rack.input  
#<StringIO:0x007fccd040f1d8>
rack.logger     
#<Rack::NullLogger:0x00000000d84ed8 @app=#<Rack::Session::Cookie:0x00000000d85090 @secrets=["4c6b0b5ddac924a56d61feeafa250b789a865aab7fde04d428baec6be878db8a1c99126cca004d1ad2d0901e00166f2a195cd19826e1993026fbfa2d46f67600"], @coder=#<Rack::Session::Cookie::Base64::Marshal:0x00000000d84ff0>, @app=#<Rack::Protection::FrameOptions:0x00000000d85180 @app=#<Rack::Protection::HttpOrigin:0x00000000d851f8 @app=#<Rack::Protection::IPSpoofing:0x00000000d85298 @app=#<Rack::Protection::JsonCsrf:0x00000000d85310 @app=#<Rack::Protection::PathTraversal:0x00000000d85478 @app=#<Rack::Protection::RemoteToken:0x00000000d85590 @app=#<Rack::Protection::SessionHijacking:0x00000000d85860 @app=#<Rack::Protection::XSSHeader:0x00000000d85b30 @app=#<Rack::Flash:0x00000000d778c8 @app=#<TaskwarriorWeb::App:0x000000012b9818 @default_layout=:layout, @app=nil, @template_cache=#<Tilt::Cache:0x000000012b97f0 @cache={}>>, @opts={}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :xss_mode=>:block, :nosniff=>true, :except=>[]}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :tracking_key=>:tracking, :encrypt_tracking=>true, :track=>["HTTP_USER_AGENT", "HTTP_ACCEPT_ENCODING", "HTTP_ACCEPT_LANGUAGE"], :except=>[]}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :except=>[]}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :except=>[]}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :except=>[]}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :except=>[]}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :except=>[]}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :frame_options=>:sameorigin, :except=>[]}, @frame_options="SAMEORIGIN">, @default_options={:path=>"/", :domain=>nil, :expire_after=>nil, :secure=>false, :httponly=>true, :defer=>false, :renew=>false, :sidbits=>128, :secure_random=>SecureRandom, :secret=>"4c6b0b5ddac924a56d61feeafa250b789a865aab7fde04d428baec6be878db8a1c99126cca004d1ad2d0901e00166f2a195cd19826e1993026fbfa2d46f67600", :coder=>#<Rack::Session::Cookie::Base64::Marshal:0x00000000d84ff0>}, @key="rack.session", @cookie_only=true, @sidbits=128, @sid_secure=SecureRandom, @sid_length=32>>
rack.multiprocess   
false
rack.multithread    
true
rack.request.cookie_hash    
{"rack.session"=>"BAh7B0kiD3Nlc3Npb25faWQGOgZFRiJFZmFhN2E2ZTQzNWNjMDVjOTdmNGI1\nYmQ0ZDc1MjgxY2Q5NDY0MjI4YzQ5MDJjYTg5MzEyMjAzN2RmYTQyNWM4YUki\nDXRyYWNraW5nBjsARnsISSIUSFRUUF9VU0VSX0FHRU5UBjsARiItZmEwMjcx\nZTZjYjcxOTg5YmRkYmNmMThjODI3NjZjZGU3NjQwMWNiNkkiGUhUVFBfQUND\nRVBUX0VOQ09ESU5HBjsARiItYTBiZmM4NzZkNjhmZTdhZWE3MDBkYTVlYTg5\nMjVhYmFjNmYyZjc5NEkiGUhUVFBfQUNDRVBUX0xBTkdVQUdFBjsARiItYWJm\nMDQ5YzA0M2QzZDVlM2RhNzkyNjU4N2VkYjRhMmM5OThhMTIyYQ==\n--ef3d5b870adc10cba280e0ef95861f98201af55b"}
rack.request.cookie_string  
rack.session=BAh7B0kiD3Nlc3Npb25faWQGOgZFRiJFZmFhN2E2ZTQzNWNjMDVjOTdmNGI1%0AYmQ0ZDc1MjgxY2Q5NDY0MjI4YzQ5MDJjYTg5MzEyMjAzN2RmYTQyNWM4YUki%0ADXRyYWNraW5nBjsARnsISSIUSFRUUF9VU0VSX0FHRU5UBjsARiItZmEwMjcx%0AZTZjYjcxOTg5YmRkYmNmMThjODI3NjZjZGU3NjQwMWNiNkkiGUhUVFBfQUND%0ARVBUX0VOQ09ESU5HBjsARiItYTBiZmM4NzZkNjhmZTdhZWE3MDBkYTVlYTg5%0AMjVhYmFjNmYyZjc5NEkiGUhUVFBfQUNDRVBUX0xBTkdVQUdFBjsARiItYWJm%0AMDQ5YzA0M2QzZDVlM2RhNzkyNjU4N2VkYjRhMmM5OThhMTIyYQ%3D%3D%0A--ef3d5b870adc10cba280e0ef95861f98201af55b
rack.request.query_hash     
{}
rack.request.query_string   
rack.run_once   
false
rack.session    
{"session_id"=>"faa7a6e435cc05c97f4b5bd4d75281cd9464228c4902ca893122037dfa425c8a", "tracking"=>{"HTTP_USER_AGENT"=>"fa0271e6cb71989bddbcf18c82766cde76401cb6", "HTTP_ACCEPT_ENCODING"=>"a0bfc876d68fe7aea700da5ea8925abac6f2f794", "HTTP_ACCEPT_LANGUAGE"=>"abf049c043d3d5e3da7926587edb4a2c998a122a"}}
rack.session.options    
{:path=>"/", :domain=>nil, :expire_after=>nil, :secure=>false, :httponly=>true, :defer=>false, :renew=>false, :sidbits=>128, :secure_random=>SecureRandom, :secret=>"4c6b0b5ddac924a56d61feeafa250b789a865aab7fde04d428baec6be878db8a1c99126cca004d1ad2d0901e00166f2a195cd19826e1993026fbfa2d46f67600", :coder=>#<Rack::Session::Cookie::Base64::Marshal:0x00000000d84ff0>}
rack.session.unpacked_cookie_data   
{"session_id"=>"faa7a6e435cc05c97f4b5bd4d75281cd9464228c4902ca893122037dfa425c8a", "tracking"=>{"HTTP_USER_AGENT"=>"fa0271e6cb71989bddbcf18c82766cde76401cb6", "HTTP_ACCEPT_ENCODING"=>"a0bfc876d68fe7aea700da5ea8925abac6f2f794", "HTTP_ACCEPT_LANGUAGE"=>"abf049c043d3d5e3da7926587edb4a2c998a122a"}}
rack.url_scheme     
http
rack.version    
[1, 2]
sinatra.accept  
[text/html, application/xhtml+xml, application/xml, */*]
sinatra.error   
#<Encoding::InvalidByteSequenceError: "\xC3" on US-ASCII>
sinatra.route   
GET /tasks/:status/?
x-rack.flash    
#<FlashHash @values={} @cache={}>

You're seeing this error because you have enabled the show_exceptions setting.
```

I'm using following versions:
rack 1.2
sinatra 1.4.3
vegas 0.1.11

Can you fix it?

If you've questions or need some further informations, contact me.

Thanks.

**Comment by Zebradil** [comment] 2018-05-06 23:16
Can't reproduce the error. Task-web is running in docker with empty environment. I tried to add task with text and project contain unicode symbols:

<img width="502" alt="screen shot 2018-05-07 at 01 14 19" src="https://user-images.githubusercontent.com/1475583/39678819-39d18054-5194-11e8-9658-a00e45fe0fa0.png">
<img width="428" alt="screen shot 2018-05-07 at 01 15 03" src="https://user-images.githubusercontent.com/1475583/39678820-39ec3ffc-5194-11e8-8335-f58e2ef1fe2a.png">

**Comment by Zebradil** [comment] 2018-05-06 23:17
Closing it for now.

**Closed by Zebradil** 2018-05-06 23:17 UTC
Labels: bug
